//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionSystemLicense
    {
        public int ID { get; set; }
        public string PcCode { get; set; }
        public string LicenseActive { get; set; }
        public System.DateTime DateActive { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public bool IsActive { get; set; }
    }
}
