//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleFoodOnline
    {
        public long ID { get; set; }
        public Nullable<long> SaleFoodIDFact { get; set; }
        public string NumFish { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<System.TimeSpan> SaleTime { get; set; }
        public Nullable<long> SumPriceBase { get; set; }
        public Nullable<long> SumNet { get; set; }
        public Nullable<long> SumDiscount { get; set; }
        public Nullable<long> SumNetPrice { get; set; }
        public Nullable<long> SumPrice { get; set; }
        public string TypeFactor { get; set; }
        public string CustomerName { get; set; }
        public string CustomerTell { get; set; }
        public string CustomerAddress { get; set; }
        public Nullable<bool> PrintState { get; set; }
        public Nullable<int> StateDelivery { get; set; }
        public string Description { get; set; }
    }
}
