//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleFoodOnlineDetaile
    {
        public long ID { get; set; }
        public Nullable<long> SaleFoodID { get; set; }
        public string FoodName { get; set; }
        public Nullable<double> NumFood { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<long> NetPrice { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public Nullable<decimal> TaxPrice { get; set; }
        public Nullable<long> SumPrice { get; set; }
        public string DescFood { get; set; }
    }
}
