//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAnbar
    {
        public tblAnbar()
        {
            this.TblKalas = new HashSet<TblKala>();
        }
    
        public long ID_Anbar { get; set; }
        public string NameAnbar { get; set; }
        public string Adress { get; set; }
    
        public virtual ICollection<TblKala> TblKalas { get; set; }
    }
}
