//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblChild_KharidKala
    {
        public long ChildKharidKala_ID { get; set; }
        public Nullable<long> ChildKharidKala_KalaID { get; set; }
        public Nullable<long> ChildKharidKala_ParentID { get; set; }
        public Nullable<long> ChildKharidKala_VahedAsliKala { get; set; }
        public Nullable<double> ChildKharidKala_TedadAsli { get; set; }
        public Nullable<long> ChildKharidKala_VahedFareKala { get; set; }
        public Nullable<double> ChildKharidKala_TedadFare { get; set; }
        public string ChildKharidKala_SharhKala { get; set; }
        public Nullable<long> ChildKharidKala_GheymatPaye { get; set; }
        public Nullable<long> ChildKharidKala_JameMablagh { get; set; }
        public Nullable<long> ChildKharidKala_TakhfifMablagh { get; set; }
        public Nullable<double> ChildKharidKala_TakhfifDarsad { get; set; }
        public Nullable<long> ChildKharidKala_MablaghPasAsTakhfif { get; set; }
        public Nullable<long> ChildKharidKala_MaliyatMablagh { get; set; }
        public Nullable<double> ChildKharidKala_MaliyatDarsad { get; set; }
        public Nullable<long> ChildKharidKala_JameKol { get; set; }
    
        public virtual TblKala TblKala { get; set; }
        public virtual TblParent_KharidKala TblParent_KharidKala { get; set; }
        public virtual TblVahedKalaAsli TblVahedKalaAsli { get; set; }
        public virtual TblVahedKalaAsli TblVahedKalaAsli1 { get; set; }
    }
}
