//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompany_Info
    {
        public int Company_ID { get; set; }
        public byte[] Company_Logo { get; set; }
        public string Company_Name { get; set; }
        public string Company_CodeEghtesadi { get; set; }
        public string Company_MeliID { get; set; }
        public string Company_Tel { get; set; }
        public string Company_Mail { get; set; }
        public string Company_X { get; set; }
        public string Company_Y { get; set; }
        public string Company_CodeSabt { get; set; }
        public string Company_Address { get; set; }
        public string Company_BankCard { get; set; }
        public string Company_HesabBanki { get; set; }
        public string Company_Text { get; set; }
        public string IpServer { get; set; }
        public Nullable<bool> EnableServer { get; set; }
    }
}
