//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContact
    {
        public tblContact()
        {
            this.tblAdresses = new HashSet<tblAdress>();
            this.tblMobiles = new HashSet<tblMobile>();
            this.tblTells = new HashSet<tblTell>();
        }
    
        public long Contacts_ID { get; set; }
        public string FullName { get; set; }
        public int Pishvand_ID { get; set; }
        public Nullable<int> Tafzili_ID { get; set; }
        public Nullable<int> Know_ID { get; set; }
        public Nullable<int> GroupContact { get; set; }
        public Nullable<int> ID_ZamineyeFaliyat { get; set; }
        public Nullable<bool> Haghighi { get; set; }
        public Nullable<bool> Hoghoghi { get; set; }
        public string Code_Eghtesadi { get; set; }
        public string Code_Melli { get; set; }
        public string Email { get; set; }
        public Nullable<long> SaghfeEtebar { get; set; }
        public Nullable<int> User_ID_Contacts { get; set; }
        public Nullable<short> RateContacts { get; set; }
        public byte[] ImageContact { get; set; }
        public string XYMapContact { get; set; }
        public Nullable<long> MandeAvalDovre { get; set; }
        public string StatusMande { get; set; }
        public string SerialSanadEftetahiye { get; set; }
        public Nullable<System.DateTime> Date_Birth { get; set; }
        public Nullable<System.DateTime> Date_Marid { get; set; }
        public Nullable<bool> Status_Marid { get; set; }
        public double DiscountPercent { get; set; }
    
        public virtual ICollection<tblAdress> tblAdresses { get; set; }
        public virtual ICollection<tblMobile> tblMobiles { get; set; }
        public virtual ICollection<tblTell> tblTells { get; set; }
        public virtual tblTafzili tblTafzili { get; set; }
    }
}
