//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblChild_ForooshKala
    {
        public long ChildForooshKala_ID { get; set; }
        public long ChildForooshKala_KalaID { get; set; }
        public Nullable<long> ChildForooshKala_ParentID { get; set; }
        public string ChildForooshKala_SharhKala { get; set; }
        public Nullable<double> ChildForooshKala_TedadAsli { get; set; }
        public Nullable<long> ChildForooshKala_GheymatPaye { get; set; }
        public Nullable<long> ChildForooshKala_JameMablagh { get; set; }
        public Nullable<long> ChildForooshKala_TakhfifMablagh { get; set; }
        public Nullable<double> ChildForooshKala_TakhfifDarsad { get; set; }
        public Nullable<long> ChildForooshKala_MablaghPasTakhfif { get; set; }
        public Nullable<long> ChildForooshKala_MaliyatMablagh { get; set; }
        public Nullable<double> ChildForooshKala_MaliyatDarsad { get; set; }
        public Nullable<long> ChildForooshKala_JameKol { get; set; }
        public string ProductName { get; set; }
    
        public virtual TblKala TblKala { get; set; }
        public virtual TblParent_FrooshKala TblParent_FrooshKala { get; set; }
    }
}
