//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblExpAshpazkhane
    {
        public long ID { get; set; }
        public string Mavad1 { get; set; }
        public string Mavad2 { get; set; }
        public string Mavad3 { get; set; }
        public string Mavad4 { get; set; }
        public string Mavad5 { get; set; }
    }
}
