//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGroupKala
    {
        public TblGroupKala()
        {
            this.TblKalas = new HashSet<TblKala>();
        }
    
        public long ID_Group { get; set; }
        public string NameGroup { get; set; }
        public string TypeGroup { get; set; }
        public byte[] ImageGroup { get; set; }
    
        public virtual ICollection<TblKala> TblKalas { get; set; }
    }
}
