//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKardeksKala
    {
        public long Kardekskala_ID { get; set; }
        public Nullable<System.DateTime> Kardekskala_Date { get; set; }
        public Nullable<long> Kardekskala_NumFact { get; set; }
        public string Kardekskala_TypeFact { get; set; }
        public Nullable<long> Kardekskala_KalaID { get; set; }
        public string Kardekskala_Vahed { get; set; }
        public Nullable<double> Kardekskala_Varede { get; set; }
        public Nullable<double> Kardekskala_Sadere { get; set; }
        public Nullable<double> Kardekskala_Mande { get; set; }
        public Nullable<long> Kardekskala_GheymatTamamShode { get; set; }
    
        public virtual TblKala TblKala { get; set; }
    }
}
