//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKala
    {
        public TblKala()
        {
            this.TblChild_ForooshKala = new HashSet<TblChild_ForooshKala>();
            this.TblChild_KharidKala = new HashSet<TblChild_KharidKala>();
            this.TblKardeksKalas = new HashSet<TblKardeksKala>();
            this.tblPriceChangeKalas = new HashSet<tblPriceChangeKala>();
        }
    
        public long ID_Kala { get; set; }
        public string Name_Kala { get; set; }
        public Nullable<long> Fk_GroupKala { get; set; }
        public Nullable<long> Fk_VahedKalaAsli { get; set; }
        public Nullable<long> Fk_Anbar { get; set; }
        public Nullable<long> GheymatKharidAsli { get; set; }
        public Nullable<long> GheymatForoshAsli { get; set; }
        public Nullable<int> DarsadTakhfif { get; set; }
        public Nullable<int> DarsadMaliyat { get; set; }
        public Nullable<bool> MoafMaliyat { get; set; }
        public Nullable<int> HadaghalMovjodi { get; set; }
        public Nullable<bool> ControlCount { get; set; }
        public byte[] Picture { get; set; }
        public string Serial_kala { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Tozihat { get; set; }
        public Nullable<double> MojodiAvalDore { get; set; }
        public string MianginFiAvalDovre { get; set; }
        public string SerialSanadEftetahiye { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public double PercentProfit { get; set; }
    
        public virtual ICollection<TblChild_ForooshKala> TblChild_ForooshKala { get; set; }
        public virtual ICollection<TblChild_KharidKala> TblChild_KharidKala { get; set; }
        public virtual TblGroupKala TblGroupKala { get; set; }
        public virtual TblVahedKalaAsli TblVahedKalaAsli { get; set; }
        public virtual ICollection<TblKardeksKala> TblKardeksKalas { get; set; }
        public virtual ICollection<tblPriceChangeKala> tblPriceChangeKalas { get; set; }
    }
}
