//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMobile
    {
        public int Mobile_ID { get; set; }
        public int Contacts_ID { get; set; }
        public string MobileNumber { get; set; }
    
        public virtual tblContact tblContact { get; set; }
    }
}
