//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPriceChangeKala
    {
        public long ID { get; set; }
        public Nullable<long> ID_Kala { get; set; }
        public Nullable<double> Count_Kala { get; set; }
        public Nullable<long> Price_Kala { get; set; }
        public Nullable<long> SumPrice { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Is_Zero { get; set; }
    
        public virtual TblKala TblKala { get; set; }
    }
}
