//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblParent_FrooshKala
    {
        public TblParent_FrooshKala()
        {
            this.TblChild_ForooshKala = new HashSet<TblChild_ForooshKala>();
        }
    
        public long ForooshKalaParent_ID { get; set; }
        public Nullable<long> ForooshKalaParent_Tafzili { get; set; }
        public Nullable<System.DateTime> ForooshKalaParent_Date { get; set; }
        public string ForooshKalaParent_Tozih { get; set; }
        public long ForooshKalaParent_JameMablaghPaye { get; set; }
        public Nullable<long> ForooshKalaParent_JameMaliyat { get; set; }
        public Nullable<long> ForooshKalaParent_JameTakhfif { get; set; }
        public Nullable<long> ForooshKalaParent_JameMablaghPasTakhfif { get; set; }
        public Nullable<long> ForooshKalaParent_JameKol { get; set; }
        public Nullable<long> ForooshKalaParent_JameService { get; set; }
        public Nullable<long> ForooshKalaParent_UserId { get; set; }
        public string ForooshKalaParent_SerialSanad { get; set; }
        public string ForooshKalaParent_ShomareMiz { get; set; }
        public string ForooshKalaParent_ModateEntezar { get; set; }
        public Nullable<long> ForooshKalaParent_ShomareFish { get; set; }
        public string ForooshKalaParent_StatusFact { get; set; }
        public Nullable<System.TimeSpan> ForooshKalaParent_Time { get; set; }
        public string ForooshKalaParent_TypeFact { get; set; }
        public string ForooshKalaParent_SelectedAdress { get; set; }
        public string ForooshKalaParent_SelectedTell { get; set; }
        public string ForooshKalaParent_NumberPager { get; set; }
        public string ForooshKalaParent_Tahvilgirande { get; set; }
        public Nullable<bool> ForooshKalaParent_TasvieFact { get; set; }
        public Nullable<bool> ForooshKalaParent_Ready { get; set; }
        public Nullable<bool> ForooshKalaParent_Delivery { get; set; }
    
        public virtual ICollection<TblChild_ForooshKala> TblChild_ForooshKala { get; set; }
    }
}
