//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParentSanad
    {
        public tblParentSanad()
        {
            this.tblChildeSanads = new HashSet<tblChildeSanad>();
        }
    
        public long Serial_Sanad { get; set; }
        public Nullable<long> Number_Sanad { get; set; }
        public Nullable<int> StatusSanadID { get; set; }
        public Nullable<int> TypeSanad_ID { get; set; }
        public Nullable<System.DateTime> Date_Sanad { get; set; }
        public string Time_Sanad { get; set; }
        public string Exption_Sanad { get; set; }
        public Nullable<bool> Taraz_Sanad { get; set; }
        public Nullable<bool> Error_Sanad { get; set; }
        public Nullable<bool> Edited_Sanad { get; set; }
        public Nullable<bool> Deleted_Sanad { get; set; }
        public Nullable<System.DateTime> Date_Modify { get; set; }
        public Nullable<int> User_ID { get; set; }
    
        public virtual ICollection<tblChildeSanad> tblChildeSanads { get; set; }
    }
}
