//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrinterUserSetting
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string PrinterCustomer { get; set; }
        public string PrinterSandogh { get; set; }
        public string PrinterAshpazkhane { get; set; }
        public string PrinterPeyk { get; set; }
        public Nullable<bool> BironbarMoshtari { get; set; }
        public Nullable<bool> BironbarSandogh { get; set; }
        public Nullable<bool> BironbarAshpazkhane { get; set; }
        public Nullable<bool> DakhelSalonMoshtari { get; set; }
        public Nullable<bool> DakhelSalonSandogh { get; set; }
        public Nullable<bool> DakhelSalonAshpazkhane { get; set; }
        public Nullable<bool> PeykMoshtari { get; set; }
        public Nullable<bool> PeykSandogh { get; set; }
        public Nullable<bool> PeykAshpazkhane { get; set; }
        public Nullable<bool> PeykPeyk { get; set; }
        public Nullable<bool> RePrintEdit { get; set; }
        public string StatusSefareshDefault { get; set; }
        public Nullable<bool> Sandogh5Cm { get; set; }
        public Nullable<bool> Costumer5Cm { get; set; }
        public Nullable<bool> Kitchen5Cm { get; set; }
        public Nullable<bool> Peyk5Cm { get; set; }
        public Nullable<bool> Salondar { get; set; }
    }
}
