//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSettingAcc
    {
        public int ID_ACCSetting { get; set; }
        public Nullable<int> ID_SortACC { get; set; }
        public string NameAcc { get; set; }
        public Nullable<int> Accounts_ID_Bedehkar { get; set; }
        public Nullable<int> Moein_ID_Bedehkar { get; set; }
        public Nullable<int> Tafzili_ID_Bedehkar { get; set; }
        public Nullable<int> Accounts_ID_Bestankar { get; set; }
        public Nullable<int> Moein_ID_Bestankar { get; set; }
        public Nullable<int> Tafzili_ID_Bestankar { get; set; }
        public Nullable<int> Form_ID { get; set; }
    }
}
