//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVahedKalaAsli
    {
        public TblVahedKalaAsli()
        {
            this.TblKalas = new HashSet<TblKala>();
            this.TblChild_KharidKala = new HashSet<TblChild_KharidKala>();
            this.TblChild_KharidKala1 = new HashSet<TblChild_KharidKala>();
        }
    
        public long ID_Vahed { get; set; }
        public string NameVahed { get; set; }
    
        public virtual ICollection<TblKala> TblKalas { get; set; }
        public virtual ICollection<TblChild_KharidKala> TblChild_KharidKala { get; set; }
        public virtual ICollection<TblChild_KharidKala> TblChild_KharidKala1 { get; set; }
    }
}
