//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_PrintFroosh
    {
        public Nullable<int> Contacts_ID { get; set; }
        public string FullNameContact { get; set; }
        public Nullable<System.DateTime> ForooshKalaParent_Date { get; set; }
        public string ForooshKalaParent_Tozih { get; set; }
        public long ForooshKalaParent_JameMablaghPaye { get; set; }
        public Nullable<long> ForooshKalaParent_JameMaliyat { get; set; }
        public Nullable<long> ForooshKalaParent_JameTakhfif { get; set; }
        public Nullable<long> ForooshKalaParent_JameMablaghPasTakhfif { get; set; }
        public Nullable<long> ForooshKalaParent_JameKol { get; set; }
        public Nullable<long> ForooshKalaParent_JameService { get; set; }
        public Nullable<long> ForooshKalaParent_UserId { get; set; }
        public long ID_Kala { get; set; }
        public string Name_Kala { get; set; }
        public Nullable<double> ChildForooshKala_TedadAsli { get; set; }
        public string ChildForooshKala_SharhKala { get; set; }
        public Nullable<long> ChildForooshKala_GheymatPaye { get; set; }
        public long ForooshKalaParent_ID { get; set; }
        public Nullable<long> ChildForooshKala_TakhfifMablagh { get; set; }
        public Nullable<double> ChildForooshKala_TakhfifDarsad { get; set; }
        public Nullable<long> ChildForooshKala_MablaghPasTakhfif { get; set; }
        public Nullable<long> ChildForooshKala_JameMablagh { get; set; }
        public Nullable<long> ChildForooshKala_MaliyatMablagh { get; set; }
        public Nullable<long> ChildForooshKala_JameKol { get; set; }
        public Nullable<double> ChildForooshKala_MaliyatDarsad { get; set; }
        public string Serial_kala { get; set; }
        public string ForooshKalaParent_ShomareMiz { get; set; }
        public string ForooshKalaParent_ModateEntezar { get; set; }
        public Nullable<long> ForooshKalaParent_ShomareFish { get; set; }
        public string ForooshKalaParent_StatusFact { get; set; }
        public Nullable<System.TimeSpan> ForooshKalaParent_Time { get; set; }
        public string ForooshKalaParent_TypeFact { get; set; }
        public string ForooshKalaParent_SelectedAdress { get; set; }
        public string ForooshKalaParent_SelectedTell { get; set; }
        public string ForooshKalaParent_NumberPager { get; set; }
        public string ForooshKalaParent_Tahvilgirande { get; set; }
        public long ChildForooshKala_ID { get; set; }
        public string DescriptionFood { get; set; }
        public string Pishvand { get; set; }
        public Nullable<long> ForooshKalaParent_Tafzili { get; set; }
        public Nullable<int> Tafzili_ID { get; set; }
    }
}
