//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TellMobileContact
    {
        public int Tell_ID { get; set; }
        public Nullable<long> Contacts_ID { get; set; }
        public string Tell_Contact { get; set; }
    }
}
